version: '3.7'
services:
  posts-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        EXPOSE_PORT: 8081
        NODE_VERSION: 20.10.0
    ports:
      - 8081:8081
    tty: true
    restart: on-failure
